# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: fa_blog
site_url: https://faretek1.github.io/
site_description: faretek's blog website. (you can comment by the way)

repo_url: https://github.com/FAReTek1/faretek1.github.io
repo_name: FAReTek1/faretek1.github.io

theme:
  name: material
  custom_dir: overrides

  logo: assets/logo.svg
  favicon: assets/logo.svg

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
      primary: red
      accent: red

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: red
      accent: red

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
      primary: red
      accent: red


  features:
    # - navigation.instant  # this breaks the hit counter
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - content.tabs.link
    - content.tooltips


plugins:
  - social
  - search
  - glightbox
  - meta
  - authors:
      authors_file: docs/blog/.authors.yml
      # output_page: blog/authors.md
      # yeah the above doesn't work

  - blog:
      draft: true

  - rss:
      match_path: blog/posts/.*
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags
  - mkdocs-simple-hooks:
      hooks:
        on_pre_build: "docs.hooks:on_pre_build"
        on_post_build: "docs.hooks:on_post_build"

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - pymdownx.blocks.caption
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - md_in_html

extra:
  social:
    # Took this from the goboscript mkdocs yml file
    - icon: fontawesome/brands/github
      link: https://github.com/FAReTek1/
    - icon: fontawesome/brands/discord
      link: https://discord.gg/XGKV8X9hfh
  analytics:
    provider: google
    property: G-13STQ6G21R

    feedback:
          title: Was this page helpful?
          ratings:
            - icon: material/thumb-up-outline
              name: This page was helpful
              data: 1
              note: >-
                Thanks for your feedback!
            - icon: material/thumb-down-outline
              name: This page could be improved
              data: 0
              note: >- 
                Thanks for your feedback! Help us improve this page by
                using our <a href="https://github.com/faretek1/faretek1.github.io/issues/new/?title=[Feedback]+{title}+-+{url}" target="_blank" rel="noopener">feedback form</a>.
