page_params:
  title: FA
  description: "We art the members of the blog"
  avatar_size: 150
  avatar_shape: circle
  avatar_align: left

authors:
  faretek1:
    name: FA ReTek
    description: blob
    avatar: https://github.com/faretek1.png
  areseven:
    name: FA R7
    description: blue
    avatar: https://github.com/AreSeven73.png
  loater:
    name: FA LoaTer
    description: according to all KNOW n laws of aviation, there is no way a bee should be able to fly. its wings are too small to get its fat little body off the ground. the bee, of course, flies anyway because bees don't care what humans think is impossible.
    avatar: https://github.com/FALoater.png
  know:
    name: Know
    description: accord I ng to all KNOW n L aws of aviati O n, there is no w A y a bee should be able T o fly. its wings ar E too small to get its fat little body off the g R ound. the bee, of course, fl I e S...
    avatar: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSkHB8FE6sgVry-bcG2xhxGnZTVg6MnI1QaGA&s
