authors:
  faretek1:
    name: FA ReTek
    description: blob
    avatar: https://github.com/faretek1.png
  areseven:
    name: FA R7
    description: blue
    avatar: https://github.com/AreSeven73.png
